# CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
# Use http://yaml-online-parser.appspot.com/ for validation

version: 2
jobs:
  build:
    working_directory: ~/ngx-extensions
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install-dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # - run:
      #     name: lint
      #     command: npm run lint:lib
      - run:
          name: test
          command: npm run test
      - run:
          name: coverage-report
          command: npm run coveralls
      - store_test_results:
          path: coverage
